### ISSUE TITLE
CMake warning 2 during catkin_make

### ISSUE THREAD

**Issue by patrickmckay15** [denniskrupke/ros2unity#2]
CMake Warning (dev) at ros2unity/Assets/Robots/robotiq_force_torque_sensor/CMakeLists.txt:50 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "robotiq_force_torque_sensor_gencfg" of target
  "rq_sensor" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by denniskrupke** [comment]
Not related to Unity3D. Code can not be embedded in ROS workspace.
